### ISSUE TITLE
RTF Layout

### ISSUE THREAD

**Issue by AliMD** [google/web-starter-kit#181]
Great tools ;)
Any plane for define some right to left layout helper ?

**Comment by nicolasgarnier** [comment]
IMO RTF needs to be tackled as part of an i18n guidance and I like the css-flip approach: basically you'd use css-flip to generate an RTF version of the CSS and serve that automatically when an rtf language is detected, along with the content for the language in question. Currently we don't have client-side i18n tooling/library baked-in at all. Is i18n something that we want to add to WSK or is it one of these features that we won't add because it will make WSK even more overwhelming, I'm not sure. @addyosmani do you have an opinion on that?

**Comment by addyosmani** [comment]
We've done extensive research around css-flip and RTL lately. There's enough work involved in getting this properly setup that we're going to write a guide on this rather than building it in atm. This may change at some point once the tooling is easier for entry users :)

**Comment by AliMD** [comment]
@addyosmani may I any help on this progress please ?
I'm working on rtl layouts more than 10 years on many project
And we have many research about it
I don`t use css flipping anymore because
1. As a rtl native user We hate flip all layout for example in android or gmail or etc. we usually prefer to use english version because of that.
2. In many case we want combined layout in our website and we prefer to use `dir` attribute for exception layout in some section
3. As a developer we prefer to change and develop in single project for all langs not separate css and layout file for rtl users

For example as a user I want to support rtl writing in google keep not flip all the website
Thank you in advance

**Comment by addyosmani** [comment]
@AliMD Pardon our delay on getting back to you on this. After spending a few weeks investigating RTL and i18n/l10n for our other project Material Design Lite (getmdl.io), we've decided to tackle this issue upstream there now that we're using it for layout and components. 

@gauntface has done some experimentation there and we're hopeful to bring that into the main project at some point in 2016. We'd appreciate any help with input/testing there and Matt may be able to share some links to his WIP work once it's up.
