### ISSUE TITLE
Separate Gulp Tasks in HTML, SASS, JS and Serve

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#404]
For a new developer separating the concerns to:

* HTML
* SASS
* JS
* Serving

allows them to easily delete, edit or simply learn what the gulp file is doing and allows us to become much more flexible. The main bulk of work here is to create a way of managing JS concatenation without the build blocks in HTML.

Further exploration into how way can make the gulp file feel less monolithic would be ideal.

**Comment by addyosmani** [comment]
Let's use this issue to discuss specifics. Note: there have been changes made to the build process since this issue was opened.

## Scripts

https://github.com/google/web-starter-kit/blob/material-sprint/gulpfile.js#L110

* Concat all *.js in the styleguide (Todo: update to include user scripts)
* Uglify these scripts
* Output to dist/scripts/main.min.js

Is there anything else we want this task to do? Continuing to keep JSHint separate makes sense to me.

## Sass

We don't have a `sass` task, but we do have a `styles` one: https://github.com/google/web-starter-kit/blob/material-sprint/gulpfile.js#L90

* Compiles all *.sass (and stream takes all *.css)
* Runs it through autoprefixer
* Writes it out to .tmp
* Concatenates and minifies styles
* Outputs to dist

Is there anything that needs changing here?

## HTML

The HTML task is the one I would say needs more work. 

* https://github.com/google/web-starter-kit/blob/material-sprint/gulpfile.js#L146 can probably go if we move UnCSS to the Sass step.
* I don't believe we need https://github.com/google/web-starter-kit/blob/material-sprint/gulpfile.js#L142 any more.

Anything else?

**Comment by nicolasgarnier** [comment]
This issue has been around for a while but I think it is still relevant.
I agree with the premise that we need to separate concerns (per file types) and currently it seems to me that where we fail to do that is in the HTML/Styles tasks because we are processing CSS files in both tasks.

IMO simply moving uncss to 'styles' would make sure we have separate tasks for HTML - CSS - JS.

I can try to tackle this if you guys think we want this and that there are no foreseeable bad side effects.

**Comment by addyosmani** [comment]
Per offline conversations with @gauntface, next year we're going to take WSK back in the direction of being more focused on a solid, reusable build process. A split-file Gulpfile where you can compose a new project out of different files (optimise-images.js, minify-css.js, minify-js.js, transpile-es2015.js etc) may well be what we end up with. For the 0.6.0 line of WSK (current), we're not going to opt for any changes here until then.
