### ISSUE TITLE
Consider releasing on Bower

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#423]
Would be helpful for anyone using WSK to add support for versioning.

**Comment by nicolasgarnier** [comment]
Has anyone had more thoughts about this? Lets try to move this forward or close the issue since it's been opened for a year :) I guess we have the choice between:

 - Close and do nothing, people are happy using master directly (living on the bleeding edge) or use the GitHub API to get the latest tag.
 - Create a `stable` branch when we release 0.6.0

**Comment by addyosmani** [comment]
After thinking this over, I think the first of these options above makes the most sense. We're a boilerplate project meant to be forked and changed with your own versioning. Including our versions out of the box will (unfortunately) result in quite a few folks publishing projects that don't alter this info at all and that's probably not a great idea. 

With respect to how other tools get us, I'm in favour of pushing a `stable` branch for other tools to use (but will strongly encourage them to use tags as that's far more reliable). We'll tackle this along with the 0.6.0 release.
