### ISSUE TITLE
Unifying paths for components.[css|scss] ?

### ISSUE THREAD

**Issue by sethladd** [google/web-starter-kit#429]
Hi,

Playing around with WSK, thanks for the tool!

One bit that was confusing:

In styleguide.html, I see this:

`<link rel="stylesheet" href="styles/components.css">`

But when I look inside `app/styles` I see a directory called `components`

I was expecting to see `app/styles/components.scss` which would be a really nice mapping between the SCSS file on disk and the CSS file mentioned in styleguide.html

Not sure if there's a good reason to map `styles/components.css` to `app/styles/components/components.scss` but if it's not a big deal, I'd love to have the same paths to the same files (module the extension)

**Comment by addyosmani** [comment]
Apparently, using `async` when the script tag is already at the bottom of the page allows it to be discoverable by the preloader. This means if the parser is blocked at some earlier point, the script can still be discovered and requested before the parser gets to it. 

My only concern with advocating for `async` use at the bottom of the page is if we have more than one script tag in production (we likely won't, but may) and both are `async`, afaik, there isn't a guarantee that they will execute in the right order. 

cc @igrigorik who may be able to provide more insight into this than I have :)

**Comment by addyosmani** [comment]
In the material-sprint branch, component styles live in individual directories https://github.com/google/web-starter-kit/tree/material-sprint/app/styleguide which are loaded in via https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/styleguide.scss per your needs, on a pick and mix basis.

When you `gulp` (build) the styles, they end up in a `dist/styles/main.css` file along with any other user styles that may have been authored. The basic premise is that rather than there being a 1:1 mapping (which would result in... /styleguide/styleguide.css, /styles/userstyles.css etc), you have a single set of CSS you include in your final page. 

This seems relatively easy to parse for a user, but I'm interested in hearing whether this introduces other challenges for integrations that consume us.

**Comment by nicolasgarnier** [comment]
Hey @sethladd,

The styles section of WSK has changed a lot since we're now importing/using Material Design Lite as an external dependency. I'll close this but please let me know if there are any related issues.
