### ISSUE TITLE
Consider adding <meta name="msapplication-tap-highlight" content="no">

### ISSUE THREAD

**Issue by ebidel** [google/web-starter-kit#556]
To turn off tap highlight on windows 8 IE

**Comment by nicolasgarnier** [comment]
Since we've switched the UI components part to using [Material Design Lite](https://github.com/google/material-design-lite) (MDL) and since MDL does set active state on elements and (optionally) shows ripples on touch it seems we are OK adding `<meta name="msapplication-tap-highlight" content="no">`. I'm sending a PR.
