### ISSUE TITLE
material: multi-row layout header disappears with narrow width

### ISSUE THREAD

**Issue by sethladd** [google/web-starter-kit#615]
Trying out the material branch. Good stuff! However, I ran into what might be a bug?

Trying out http://localhost:3000/styleguide/layout/demo.html

Narrow the width of my browser.

Scroll down to multi-row layout.

See screenshot. Shouldn't I see a dark-blue header?

![screen shot 2015-01-23 at 1 24 36 pm](https://cloud.githubusercontent.com/assets/5479/5883016/681e211c-a303-11e4-989b-d8c4e2d918fe.png)

**Comment by addyosmani** [comment]
Thanks for the bug report. @sgomes could you take a look please?

**Comment by sgomes** [comment]
Ah, that one was actually by design, because in my mind it didn't make a lot of sense to have a 3-line-high header in a mobile layout. Perhaps I should make the text clearer in explaining that the multiple rows are only visible in desktop.

If you'd really like to show them in mobile, though, you could make that happen simply by adding the [wsk-layout--fixed-header](https://github.com/google/web-starter-kit/blob/material-sprint/app/styleguide/layout/README.md#options) option.

**Comment by sgomes** [comment]
Clarification added.
