### ISSUE TITLE
Build tooling is hostile to WebWorkers and ServiceWorker

### ISSUE THREAD

**Issue by PaulKinlan** [google/web-starter-kit#617]
I built QRSnapper the other day and I need to push a whole load of work in to a webworker (and also a service worker).

gulp serve is fine, but a dist build using `gulp` will concatenate all the files which means a subsequent importScripts will fail.  This is an issue because your only sane option at the moment is to exclude all the files used in importScripts from concatenation.  

Another example in a service worker if I do a cache.addAll and provide a list of files, it will error because the list of files you add in is either for build time or deploy time.  It's a pain.

It's not hard to work around but you have to work around the issues and that is a problem if you come to WSK.

**Comment by addyosmani** [comment]
cc @jeffposnick who is working on adding SW support in #613. 

> a dist build using gulp will concatenate all the files which means a subsequent importScripts will fail

We should definitely fix this. One goal with the sw-precache work is that this shouldn't be an issue.

> Another example in a service worker if I do a cache.addAll and provide a list of files, it will error because the list of files you add in is either for build time or deploy time. It's a pain.

Jeff, I want to say this shouldn't be an issue if you're pre-specifying files to be cached upfront with the precache tooling, but am interested in your insights here.

**Comment by addyosmani** [comment]
Also, thanks for the report, Paul :)

**Comment by PaulKinlan** [comment]
np - as a side note, WSK made things a lot easier :)

**Comment by PaulKinlan** [comment]
One thing to note, is that sw-precache doens't iirc help with the importScripts concatenation issues.

**Comment by jeffposnick** [comment]
Hey @PaulKinlan, I think `sw-precache` should help for the scenario you're describing. If it doesn't, I'll modify it so that it does.

One of the params you can pass in to `sw-precache` is [`importScripts`](https://github.com/jeffposnick/sw-precache#importscripts-arraystring). What you'd want to do, if I understand your use case, is pass in the path to your concatenated scripts using that parameter. I've done similar in the past with another project.

`sw-precache` works best when you call it as the very last step in your build process, after all CSS/JS/whatever has been minified and concatenated, so that you know the final paths to all the resources.

**Comment by addyosmani** [comment]
We've since landed support for sw-precache. If there's further feedback on how it can be improved, I recommend we open an issue upstream and update WSK as and when needed.
