### ISSUE TITLE
ripple-background for wks-item is missing

### ISSUE THREAD

**Issue by MikeMitterer** [google/web-starter-kit#654]
Without background set:

![screenshot-1687](https://cloud.githubusercontent.com/assets/116654/6552858/c26b3046-c64a-11e4-933a-f1747c1f92ce.png)

Here how it should look like:
![screenshot-1692](https://cloud.githubusercontent.com/assets/116654/6552866/ddf274a0-c64a-11e4-9459-d3a7a779d3ae.png)

My proposal starts on line 54:
https://github.com/MikeMitterer/dart-wsk-material/blob/master/lib/sass/item/_item.scss

**Comment by addyosmani** [comment]
Thanks for filing this issue. As part of our move to the new CSS library this summer https://github.com/google/web-starter-kit/issues/674, we're closing issues related to the 0.5.x styles, which will no longer be supported moving forward. We recommend holding off on PRs to the styles in master as they're going to be replaced by something much better soon.

If this issue is still present in MDL, please file a new issue there.
