### ISSUE TITLE
As hard to use as Bootstrap

### ISSUE THREAD

**Issue by David263** [google/web-starter-kit#667]
Bootstrap is very low-level: all the CSS, JavaScript, and other pieces and the many limitations have to be understood in detail and written manually. But WSK is just as bad an experience for Windows users, as the instructions appear to assume the use of Linux and deep familiarity with Linux development environments.

I wouldn't make an issue of these facts if it weren't for the unqualified claims that are made in all the intro material. We Windows users just assume that everything will just work, and will not require Linux. It is rough when we download WSK and discover the truth.

I strongly suggest that all the intro documentation be edited to reveal that this is a Linux-only development structure.

I think the truth is that no really easy-to-use development environment for responsive Web design exists. Many days of Web searching has led me to this conclusion.

**Comment by David263** [comment]
An additional limitation not disclosed up front: the instant editing feature requires installation of a specific editor (Sublime) for a charge of $70 (with free trial). Its description sounds nowhere as extensible as Emacs; the emphasis is on selling it on the basis of a few flashy features. Note that many editors, such as the free Arachnophilia, support instant Web editing.

This little bit of hidden moneymaking is only offensive because iof the glowing generalities of the intro descriptions of this package, described above in the issue description, which actually does not include Sublime.

**Comment by sindresorhus** [comment]
Please include specifics. Also be aware that your rant comes very much off as ignorant trolling and is very hard to take seriously, but I'll bite. What specific problems did you encounter?

**Comment by patrickjaja** [comment]
Well I am using WSK in Windows 7 x64 with Netbeans and Eclipse and all i had to do was running the commands described in the readme.
Btw live reload is not a feature of sublime text.

**Comment by Garbee** [comment]
> An additional limitation not disclosed up front: the instant editing feature requires installation of a specific editor (Sublime) for a charge of $70 (with free trial).

This is only presented as an *example*. The developer is free to chose whichever editor they wish and if it supports live-reload then they can get that integrated just fine.

> This little bit of hidden moneymaking is only offensive because if the glowing generalities of the intro descriptions of this package, described above in the issue description, which actually does not include Sublime.

Um, who is making the money if people buy a Sublime License? Not anyone working on this project. We push ST since it is a *very* capable editor that is cross-platform and easy to use. Vim and emacs, as you suggest as preference, are not nearly as easy to use. We can't recommend them for the beginners the documentation is built for. Instead of recommending three or four editors to cover different platforms, we pick one that works across them all nicely. This makes documentation and helping others along much easier.

> I strongly suggest that all the intro documentation be edited to reveal that this is a Linux-only development structure.

As @sindresorhus requested, please provide specific examples. It sounds as if by "intro material" you are talking about Web Fundamentals, not WSK. WSK's [intro doc](https://github.com/google/web-starter-kit/blob/master/docs/install.md) should be straightforward enough to follow in any OS. Install NodeJS, npm should then be in your global path and you can run the other necessary commands.

> I wouldn't make an issue of these facts if it weren't for the unqualified claims that are made in all the intro material.

What are the "unqualified claims"? Probably will refer to the previous request for specifics. We can't fix vague references. Providing specific pieces of content will help us understand what needs to be improved.

----------

We are working to make things much better with version 0.6 by having an out-of-the-box experience that doesn't require any external software from npm. This has been planned at least for a few weeks now, covered in issue #660.

**Comment by Flaiker** [comment]
Using WSK with Win7 x64 and Win8.1 x64 with WebStorm and it works just fine (including live reload, gulp and jshintrc integration etc.).

Though I agree it can be quite a pain to setup, but that's mostly Ruby for Windows fault in my opinion (see [this](https://gist.github.com/fnichol/867550) which I had to do, I needed to fully uninstall Cygwin and its own Ruby distribution so they don't conflict and also #649 was also bugging me back then and making things difficult).

Seems like #660 will make things quite a bit easier in general though.

**Comment by Garbee** [comment]
@Flaiker I do believe we have done away with the Ruby dependency. I think it was only necessary for Sass, but we have since switched to lib-sass from node.

**Comment by fsquaredmedia** [comment]
Actually WSK works good on Windows. I use a mac and my Dev team uses windows. You may not be able to run it on IIS but since it is a front-end framework just complete your HTMLs before Back-end gets their hands on the. Here are the instructions I gave my Windows Dev Team. Read it carefully as there are some issues when working with a team that uses both platforms (Mac/Windows). 

### Installing Git:
Download the latest Windows build Here: 
http://git-scm.com/downloads

Start The installation....

Once you reach the 'Adjusting you PATH environment' section select the 'Run git and included Unix tools' from the Windows command prompt.

Next, under 'Configuring the line ending conversions' make sure 'Checkout Windows-style commit Unix-style line endings' is selected.

Should complete the install for git. In cmd type 'git --version' to confirm installation


### Install Node and NPM

Download the latest windows build here:
https://nodejs.org/

Installation process is simple with no special instructions. 

type 'node -v' to see version of node and confirm install
type 'npm -v' to see version of npm (installed with node) and confirm install

### Install Ruby and  Gems (Required for SASS)

Download the Ruby 1.9.3 (for compatibility) build for windows here:
http://rubyinstaller.org/

Installation process is simple with no special instructions. 

type 'ruby -v' to see version of ruby and confirm install
type 'gem -v' to see version of gem (installed with ruby) and confirm install


### Installing Sass

type 'gem install sass' into your cmd (you may have to run as Admin) 

type 'sass -v' to see version of sass and confirm install


### Install GulpJS
In cmd type 'npm install -g gulp' if you get errors install as admin

type 'gulp -v' to verify

### Install Bower
In cmd type 'npm install -g bower' if you get errors install as admin

type 'bower -v' to verify

### Generating SSH Key (For working with REPOS and Server)

To generate an SSH key with PuTTYgen, follow these steps:
1. Open the PuTTYgen program.
2. For Type of key to generate, select SSH-2 RSA.
3. Click the Generate button.
4. Move your mouse in the area below the progress bar. ...
5. Type a passphrase in the Key passphrase field. ...
6. Click the Save private key button to save the private key.

**Comment by David263** [comment]
I apologize for the too-brief list of complaints that I gave here. My goal was to write a modern website (I'm a retired web designer and software engineer), and with this goal I encountered nothing but frustration in looking at what has been done to help designers. I learned that something like Bootstrap would be needed, at least.

As for WSK, I'm afraid that, with my background being mostly in Windows, I have no tolerance for working with a maze of new libraries, programming languages, and technologies, which apparently are enjoyed by those who use Linux every day. I want to use what seem like simple basics to me: PHP, Javascript, HTML, and CSS.

After about a week of intense research, including trying out Froont, which could end up being usable someday, my initial feeling that Responsive Design is still in its infancy seems well confirmed.

FWIW, I chose a methodology that allowed me to make fast progress in coding a new website: I created my own framework in PHP that localizes each part of the visible website and each internal feature, using ordinary PHP functions, for ease of debugging and extending. The actual HTML, CSS, and Javascript that are generated are mostly what are required to support each Bootstrap feature, and most of the development time is spent in figuring out what the Bootstrap documentation fails to say (which in the case of the basic Affix feature, when embedded in a real website,  is immense). Development is going so quickly that I have been able to design a great unlimited and easy to use language translation system to help our volunteers translate the website and maintain the translations easily.

I suspect that someone with more free time and expertise than myself will someday create a really universal framework for designing and implementing websites easily. It is sorely needed.

**Comment by kevva** [comment]
I'm sorry you've had a hard time getting this to work, but there's plenty of documentation and @fsquaredmedia has even wrote down the exact instructions for installing all the dependencies you'd need.

And you haven't really described what technical problems you're having. It seems like you have the wrong expectations about this. You still require some sort of web development knowledge to create an app with this.

**Comment by sindresorhus** [comment]
https://github.com/google/web-starter-kit/issues/660 might help.
