### ISSUE TITLE
Add support for ES6 using Babel 

### ISSUE THREAD

**Issue by thejameskyle** [google/web-starter-kit#689]
I can contribute a PR for this

**Comment by MattDiMu** [comment]
Any progress on this? It looks a bit strange to me, that the gulpfile is written in es6 (babel-enhanced) while the application itself still doesn't support es6.

**Comment by arthurvr** [comment]
I don't see why not. It's just JavaScript, at the end. :+1:

**Comment by appleboy** [comment]
:+1: push ..

**Comment by Garbee** [comment]
May want to just hold off on any effort here. WSK is undergoing a big change soon now that MDL is released. Let's wait and see what the team has planned for that before putting any effort into rewriting what currently exists.

**Comment by callumlocke** [comment]
@Garbee any more info about the big change? Has that happened?

**Comment by Garbee** [comment]
MDL has been made the style setup for WSK already. This was the major change, going from an internally managed component system to external. This means the need for direct babel support internally is lowered greatly since there is no real scripting occurring within WSK (just a small basic starter script.)

I believe it would be best if WSK left this alone and for developers that want babel, they can freely opt-in by editing the setup themselves (as you should be doing anyways.) Since there isn't much logic happening in WSK I don't see why we should force babel on people by default.

**Comment by thejameskyle** [comment]
It's already happened as per https://github.com/google/web-starter-kit/issues/742
