### ISSUE TITLE
IE11 flex issues and font-face issue.

### ISSUE THREAD

**Issue by brianmontana** [google/web-starter-kit#702]
The compiled component.css didn't include a reference to Roboto, so added that and shows up in all supported browsers now for the style guide.

Flex is having issues in primary content, removed it so it's no longer overlapping in IE9/10/11. Lemme know if you need more info.

Shouldn't we just utilize one style sheet for the main page and style guide, instead of creating two?

**Comment by addyosmani** [comment]
The current style-guide (using component.css) is effectively deprecated and we're focusing efforts on the replacement. This will come with #674, which we hope to get out in the coming weeks. Sorry for closing this without an actual fix for the issue, but we're hoping the current style guide to be otherwise short lived.

**Comment by brianmontana** [comment]
Sounds good, thanks for letting me know :+1:
