### ISSUE TITLE
Is web starter kit an implementation of material design?

### ISSUE THREAD

**Issue by jimbojetlag** [google/web-starter-kit#705]
We are trying to decide if we should use WSK in production. There is this material-sprint branch, which says has been moved to its own repository, but does not link to the repo. Is WSK going to have a material implementation?

If this will happen in the future, should we wait for it, or should we start with current WSK and then migrate? Would the material implementation be compatible with polymer, or would using polymer mean adding extra overhead of yet another material implementation (and hence bigger asset download size)?

**Comment by Garbee** [comment]
I'd say wait a bit. [MDL](https://developers.google.com/web/tools/material-design-lite/) is coming soon which is what WSK will take advantage of with the next release. This has been discussed in Issue #674.

**Comment by jimbojetlag** [comment]
> MDL is coming soon 

Why is it called 'Lite'? Is it not a full implementation? Also, that website looks... unfinished... well let's say not of Google quality.

> Chose Polymer or WSK/MDL

Does polymer have a standalone material implementation that can be used for website layout etc, just like a css framework?

This is really confusing. Material design is proposed by Google, and there are independent projects in Google which try to implement it independently, and none of them are complete. Why wouldn't Google just have a single decent material implementation (which won't hopefully be dropped later like other Google projects)?

**Comment by Garbee** [comment]
> Why is it called 'Lite'?

This has a few reasons, I'm sure we will have something explaining this when it is released.

> Also, that website looks... unfinished... well let's say not of Google quality.

Google is a bunch of people working on small teams trying to get stuff done. DGC (Developer.Google.Com) is going through a big shift right now with the web portal and some things still aren't finished. Give the people working on it some time. This can still be called "beta" as it were.

> Does polymer have a standalone material implementation that can be used for website layout etc, just like a css framework?

It's complicated, go read up on what Polymer is along with Web Components to understand how it works, that is getting off-topic here to go through. Once you understand what Polymer is and how it works, you can assess a given project to see if it fits in your stack. And I can't discuss MDL more until it is released, so I can't make a good comparison for you.

Material Design is still evolving for desktop, so having a few projects doing it helps find issues that need to be fixed in the specification. The different projects are actually working together in terms of understanding the specification and implementing it. It is *how* the projects follow through implementation that is different since they have different technology stacks.

**Comment by jimbojetlag** [comment]
They just announced polymer starter kit https://developers.google.com/web/tools/polymer-starter-kit/ in io. PSK comes with paper material implementation. Not sure if it's the same as MDL.

**Comment by nicolasgarnier** [comment]
Hey @jimbojetlag PSK and MDL are different. There are Polymer based Material Design implementations which PSK includes. Material Design Lite is an implementation of Material Design in vanilla JS/HTML/CSS.
