### ISSUE TITLE
Combine media queries

### ISSUE THREAD

**Issue by diegorodriguesvieira** [google/web-starter-kit#724]
Why Google Web Starter Kit do not use [gulp-combine-media-queries](https://www.npmjs.com/package/gulp-combine-media-queries) plugin?

**Comment by Garbee** [comment]
If people want that they can add it into their own workflow. WSK attempts to be a minimal workflow starter, not an entire solution so developers don't need to think about anything.

Something like this can also cause bugs in the output that are hard to track down (since it is most likely re-ordering some things which means your specificity gets messed with.) Because of that, it shouldn't be included in the core system imo.

**Comment by diegorodriguesvieira** [comment]
Thank you @Garbee
