### ISSUE TITLE
adjust to the screen shot.

### ISSUE THREAD

**Issue by stevemao** [google/web-starter-kit#740]
<img width="542" alt="screen shot 2015-08-14 at 10 28 28 pm" src="https://cloud.githubusercontent.com/assets/6316590/9273882/fe3eff7a-42d3-11e5-8583-b09820b7432b.png">

In the screenshot "Cross-device Synchronization", "Live Browser Reloading" and "Build in HTTP Server" are all talking about browser-sync? It's good to merge these three sections into one and add other modules this one is using.

**Comment by gauntface** [comment]
We are using browsersync to power all these things but the page is largely aimed to let people know the features the kit offers and those are all features. The list isn't pointing out the modules used since I don't believe that's how view web starter kit.

If anyone else thinks we should change this please reopen.
