### ISSUE TITLE
Compare ESLint and JSCS/JSHint

### ISSUE THREAD

**Issue by nicolasgarnier** [google/web-starter-kit#747]
We're currently using JSCS and JSHint on WSK but ESLint seems to be the new hotness and has been gaining grounds.

Lets quickly compare ESLint vs. JSCS+JSHint in the context of WSK and its upcoming move to enable ES6.

**Comment by sindresorhus** [comment]
From https://github.com/google/web-starter-kit/issues/742#issuecomment-132745919:

> The reason I prefer ESLint is that it covers all the JSHint rules and most of the JSCS rules in one tool that is IMHO easier to use, especially when you take advantage of [shareable configs](http://eslint.org/docs/developer-guide/shareable-configs). You could go with the [`eslint-config-xo-space`](https://github.com/sindresorhus/eslint-config-xo-space) shareable config which comes with sane defaults, if you don't want to deal with all the ESLint rules. Or go all in and use [XO](https://github.com/sindresorhus/xo) with the [`space` option](https://github.com/sindresorhus/xo#space).

**Comment by Garbee** [comment]
I prefer ESLint myself. It has a well documented customization API for developers creating custom rules for their projects. This makes it far more versatile compared to JSCS from what I can tell. I'm even working on a [Cross-browser compatibility checker](https://github.com/Garbee/Eslint-Cross-Browser-Compatibility-Checker) for ESLint, at least to what extent it can be done for JS. This kind of plugin system can be very beneficial to developers and having ESLint by default makes it easier to add the extra things developers will want in their projects.

**Comment by addyosmani** [comment]
One of the hesitations I've had with switching away from the current toolset is that with JSCS we have a one-line config option for using the Google JS styleguide. Does anyone know the state of play for achieving this using ESLint? Would one ultimately need to use something like https://gist.github.com/dmnsgn/75926316af5360c379da?

**Comment by Garbee** [comment]
I wouldn't be worried about the config length. The one-liner that JSCS provides is a convenience, but ESLint's extension model makes it a much better choice for general developers. It also would be more specific to end-users as to what the code style is exactly. `"google"` doesn't mean much. While ESLint's configuration *values* are vague as hell without reading the manual, overall you get more clarity from the configuration file in what exactly is allowed and not allowed.

IMO, the bigger thing to worry about missing is the auto-formatting option JSCS provides. ESLint is just now starting to experiment with a few rules being auto-fixed, but it isn't nearly as detailed or complete as JSCS.

**Comment by addyosmani** [comment]
> While ESLint's configuration values are vague as hell without reading the manual, overall you get more clarity from the configuration file in what exactly is allowed and not allowed.

I personally don't mind us getting more verbose if ultimately we're improving clarity if you read the docs. Despite writing a blog post about the JSCS autoformatting options, I don't think a huge number of people rely on the feature just yet.

**Comment by arthurvr** [comment]
> One of the hesitations I've had with switching away from the current toolset is that with JSCS we have a one-line config option for using the Google JS styleguide. Does anyone know the state of play for achieving this using ESLint?

I personally prefer to use Sindre's XO which I think is pretty consistent with the style here (except that we'd need to use the space option)

That said, there are so much projects using the Google styleguide that it's maybe just a good idea to publish a shared config to npm anyway...

**Comment by addyosmani** [comment]
I've started work on a shared config. As it turns out quite a few of our projects are considering switching to ESLint atm and it could be useful for the Google GitHub org to have this available to others. Will aim to get out soon.

**Comment by dancancro** [comment]
[Here's](http://dancancro.com/eslint_vs_jscs.html) the trade-off report I have for these two from my notes and the contributions of others. Let me know if you see any errors. 

If you would like to help reduce the time people spend trying to understand the differences between things, please go [here](http://www.dancancro.com/technology-questionnaires/) and complete a questionnaire about a technology you know.

**Comment by hzoo** [comment]
@addyosmani If y'all still want to use jscs, I made a issue on jscs seeing if anyone org members wanted to maintain the preset themselves https://github.com/jscs-dev/node-jscs/issues/1811. If that's something you might be interested in let us know (since you can also make your own config/preset/rules as well).

**Comment by lodestarops** [comment]
ESLint is awesome, I like that I can manually configure based on client specs. Looking forward to this update!

**Comment by dancancro** [comment]
@hzoo thanks for the corrections. I hope there are more differences. It would be pretty sad if there are two virtually equivalent tools out there that people developed separately instead of just talking to each other. What a waste of life.

> I like that I can manually configure based on client specs.

@lodestarops, is this something that can't be done with JSCS? How does configuration differ between these two products?

[Updated trade-off report](http://dancancro.com/eslint_vs_jscs.html)

**Comment by hzoo** [comment]
You basically configure it in the same way - you can override a preset's rules by setting a new value or setting the value to `false` or `null`.
I also suggested that the "google" preset could be moved to outside of JSCS so it could be updated in an external repo. Yeah we should think about combining efforts more.

**Comment by lodestarops** [comment]
@dancancro basically you can configure it more for ECMA scripting rather than JavaScript specifically, meaning it gives you more configuration options to adjust for custom styling, syntax (within ECMA) so you can use with other scripting languages. Once you get your config locked down for whatever coding style or build language you can use it across other non JavaScript projects. When I did my tests it seemed that it was easer to configure ESLint rather than JSCS. May need to do more digging than that, but I basically choose ESLint for future proofing. Especially with ECMA6, we'll see how things play out though.

**Comment by hzoo** [comment]
If anything it should be easier to configure with JSCS if you are specifically talking about support language features. In ESLint you use ecmaFeatures to determine what you want to support (http://eslint.org/docs/user-guide/configuring.html#specifying-language-options) - this is useful if you don't want to allow certain features. In JSCS you include `esnext: true` to use babel parsing (otherwise you don't do anything since esprima supports es6 as well). Maybe I'm just confused as to what you mean by configuration since normally configuration means that you can configure the types of rules to lint.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/eslint-config-google

**Comment by hzoo** [comment]
Nice :+1:! And if yall want to maintain the JSCS google preset we can move it out of the JSCS repo and into a separate module/repo and use that liked I mentioned before.

**Comment by arthurvr** [comment]
Can this be closed in favor of https://github.com/google/web-starter-kit/issues/775?

**Comment by hzoo** [comment]
Sounds like it

**Comment by addyosmani** [comment]
Yeah. Let's close.

**Comment by addyosmani** [comment]
Help welcome with #775 otherwise I'll PR next week.
