### ISSUE TITLE
JsHint failed for basically all my JS files

### ISSUE THREAD

**Issue by Mesian0** [google/web-starter-kit#758]
Hello, 
I get the problem only when I run gulp serve:dist
![gulp](https://cloud.githubusercontent.com/assets/14975113/10277063/5650959e-6b4b-11e5-859d-e2b5f13033e4.PNG)
JsHint fails for all my files, but I get no errors while running the code on a browser.
I searched in the issues for a related case, issue #634 seems to be quite the same but I can't understand the workaround provided.

I used jQuery and plugins such as OwlCarousel and Velocity.js maybe JsHint can't read non-vanilla JavaScript.

Sorry I'm a total beginner with Gulp and these kind of tools !
Thank you in advance.

**Comment by addyosmani** [comment]
Could you confirm if you're using the latest version (master) or a specific older version?

**Comment by addyosmani** [comment]
Sorry for the delay in replying to the issue you submitted. JSHint will run against any of the files dropped into your `app/scripts` directory according to the style settings defined in https://github.com/google/web-starter-kit/blob/master/.jscsrc. This currently follows the Google JS style guide, so we expect you to make style choices like using `===` instead of `==`. To work around this you can add an exclusion rule to your Gulpfile that ignores anything you put into the app/scripts/vendor directory as they probably include different styling rules.
