### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by megaghz** [google/web-starter-kit#792]
I've installed all dependecies and when run `gulp serve` I got `[17:45:41] No gulpfile found`
the gulpfile is there but there is a .babel added. Also tried to rename as gulpfile.js with no luck. Why is this?

**Comment by mrmlnc** [comment]
You installed gulp globally?

```
$ npm i -g gulp
```

**Comment by megaghz** [comment]
I solved the problem below. Now I got this error.
[12:32:11] Failed to load external module babel-core/register
[12:32:11] Failed to load external module babel/register
/Users/nico/Sites/google_web_starter_kit/web-starter-kit/gulpfile.babel.js:27
import fs from 'fs';
^^^^^^

Assuming is a path issue. How can I handle this?

**Comment by mrmlnc** [comment]
Give more information:

  * Node.js version
  * npm version
  * Output: `npm ls -g --depth=0`

**Comment by megaghz** [comment]
Node.js v5.0.0
npm 3.5.2

web-starter-kit \>npm ls -g --depth=0
/usr/local/lib
├── bower@1.7.0
├── gulp@3.9.0
└── npm@3.5.2

**Comment by mrmlnc** [comment]
This error happened because for some reason you don't have babel installed in your project, i.e. in the `node_modules` directory. Try to remove this directory and run the command `npm i`.

If this doesn't work for you, then try the following:
  1. `npm cache clean` and again `npm install`
  2.  Reinstall Gulp (`npm rm -g gulp && npm i -g gulp`)
  3. `npm i && npm i -D babel-core`

I suggest to start with item 3.

**Comment by megaghz** [comment]
All good by just exec step 3. Thanks!
