### ISSUE TITLE
Service Worker throwing 404 errors on Windows

### ISSUE THREAD

**Issue by echeese** [google/web-starter-kit#835]
Specifically, I believe the stripPrefix option of sw-precache is not being set correctly. I changed it to `rootDir + '/'` and the errors went away.

**Comment by gauntface** [comment]
cc @jeffposnick 

@echeese are you using the default sw-precache task or did you change it at all?

**Comment by echeese** [comment]
The default. The errors only show up in my browser's developer console. The application runs fine otherwise. I believe the issue is `path.sep` which is `\` on windows and `/` on other platforms.

**Comment by jeffposnick** [comment]
Thanks for reporting this!

The underlying issue is that `glob.sync()` returns file paths that unconditionally use `/` as a path separator, rather than the platform-specific `path.sep`. I ended up being too clever by attempting to strip out `path.sep`, when it should be using `/` unconditionally.

I'll file a PR for the change.

**Comment by echeese** [comment]
Fixed with PR #841
