### ISSUE TITLE
rollup + babel on WSK2

### ISSUE THREAD

**Issue by gauntface** [google/web-starter-kit#845]
@surma 

Just tried this approach on a project I'm working on and I ended up needing to change it to the following:

const commonjs = require('rollup-plugin-commonjs');
const nodeResolve = require('rollup-plugin-node-resolve');

```
.pipe(rollup({
  plugins: [
    nodeResolve({ jsnext: true }),
    commonjs()
  ]
}))
.pipe(babel({
  presets: ['es2015']
}));
```

Otherwise rollup seems to convert the import into a require call which than fails.

**Comment by ramasilveyra** [comment]
It's because `babel-preset-es2015` has the plugin [babel-plugin-transform-es2015-modules-commonjs](https://github.com/babel/babel/blob/master/packages/babel-preset-es2015/package.json#L30). A better solution maybe is use [babel-preset-es2015-rollup](https://github.com/rollup/babel-preset-es2015-rollup) instead of `babel-preset-es2015`

**Comment by ramasilveyra** [comment]
I'm not sure but maybe this problem, It's because `babel-preset-es2015` has the plugin [babel-plugin-transform-es2015-modules-commonjs](https://github.com/babel/babel/blob/master/packages/babel-preset-es2015/package.json#L30). A better solution maybe is use [babel-preset-es2015-rollup](https://github.com/rollup/babel-preset-es2015-rollup) instead of `babel-preset-es2015`.
