### ISSUE TITLE
Question about Offline support.

### ISSUE THREAD

**Issue by lockys** [google/web-starter-kit#855]
Hi, thanks for this awesome work.
The [section](https://github.com/google/web-starter-kit#browser-support) mentioned that WSK supports Safari browser, but I am curious about the offline support of Safari.
As far as I know, Safari seems not support `service worker` according to this [link](https://jakearchibald.github.io/isserviceworkerready/) now.
Does the offline support feature work on Safari if I used WSK?
Thanks!

**Comment by surma** [comment]
You won’t get automatic offline support, no. As you said, Safari does not support ServiceWorker but only AppCache. We don’t have any tooling included, but it does exist.

But since ServiceWorker are progressive enhancement, your site will work in Safari just as well (just not offline right off the bat).

**Comment by lockys** [comment]
Yes, thank you :+1:
